module.exports = {
    getstartedSidebar: [
        {
            type: "autogenerated",
            dirName: "getstarted",
        },
    ],
    guidesSidebar: [
        {
            type: "autogenerated",
            dirName: "guides",
        },
    ],
    manualsSidebar: [
        "manuals/index",
        {
            type: "category",
            label: "Upbound Crossplane",
            link: {
                type: "doc",
                id: "manuals/uxp/overview",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "manuals/uxp",
                },
            ],
        },
        {
            type: "link",
            label: "Cloud Spaces",
            href: "/cloud-spaces/overview",
        },
        {
            type: "link",
            label: "Self-Hosted Spaces",
            href: "/self-hosted-spaces/overview",
        },
        {
            type: "category",
            label: "Platform",
            link: {
                type: "doc",
                id: "manuals/platform/overview",
            },
            items: [
                {
                    type: "category",
                    label: "Identity & Access",
                    items: [
                        "manuals/platform/identity/iam",
                        "manuals/platform/identity/organizations",
                        "manuals/platform/identity/teams",
                        "manuals/platform/identity/users",
                        "manuals/platform/identity/robots",
                        "manuals/platform/identity/rbac",
                        "manuals/platform/identity/k8s-rbac",
                        "manuals/platform/identity/sso",
                        "manuals/platform/identity/oidc",
                    ],
                },
                "manuals/platform/data-residency",
            ],
        },
        {
            type: "category",
            label: "CLI",
            link: {
                type: "doc",
                id: "manuals/cli/overview",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "manuals/cli",
                },
            ],
        },
        {
            type: "category",
            label: "Official Packages",
            link: {
                type: "doc",
                id: "manuals/packages/overview",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "manuals/packages",
                },
            ],
        },
        {
            type: "category",
            label: "Marketplace",
            link: {
                type: "doc",
                id: "manuals/marketplace/overview",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "manuals/marketplace",
                },
            ],
        },
    ],
    referenceSidebar: [
        "reference/index",
        "reference/cve-policy",
        {
            type: "category",
            label: "APIs",
            link: {
                type: "doc",
                id: "reference/apis/index",
            },
            items: [
                {
                    type: "link",
                    label: "Spaces API",
                    href: "/self-hosted-spaces/reference/",
                },
                {
                    type: "autogenerated",
                    dirName: "reference/apis",
                },
            ],
        },
        "reference/cli-reference",
        "reference/pricing",
        "reference/spaces-helm-reference",
        "reference/uxp-helm-reference",
        {
            type: "category",
            label: "Release Notes",
            items: [
                {
                    type: "autogenerated",
                    dirName: "reference/release-notes",
                },
            ],
        },
        {
            type: "category",
            label: "Usage",
            items: [
                {
                    type: "autogenerated",
                    dirName: "reference/usage",
                },
            ],
        },
    ],
};
