module.exports = {
    getstartedSidebar: [
        {
            type: "autogenerated",
            dirName: "getstarted",
        },
    ],
    guidesSidebar: [
        {
            type: "autogenerated",
            dirName: "guides",
        },
    ],
    // Control Planes → UXP: just the UXP product (distribution, concepts,
    // features, how-tos, web UI). The dev workflow lives in Develop.
    uxpSidebar: [
        {
            type: "category",
            label: "Upbound Crossplane",
            link: {
                type: "doc",
                id: "controlplanes/uxp/overview",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "controlplanes/uxp",
                },
            ],
        },
    ],
    // CLI & Tooling — lives under the Control Planes dropdown, not as a top-level
    // product. Cross-cutting to all deployments: up CLI / Projects, packages, marketplace.
    developSidebar: [
        {
            type: "category",
            label: "CLI & Projects",
            link: {
                type: "doc",
                id: "controlplanes/cli/overview",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "controlplanes/cli",
                },
            ],
        },
        {
            type: "category",
            label: "Packages",
            link: {
                type: "doc",
                id: "controlplanes/packages/overview",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "controlplanes/packages",
                },
            ],
        },
        {
            type: "category",
            label: "Marketplace",
            link: {
                type: "doc",
                id: "controlplanes/marketplace/overview",
            },
            items: [
                {
                    type: "autogenerated",
                    dirName: "controlplanes/marketplace",
                },
            ],
        },
    ],
    hubSidebar: [
        "hub/overview",
        "hub/architecture",
        {
            type: "category",
            label: "Install Hub",
            items: [
                "hub/install-prereqs",
                "hub/install",
                "hub/self-hosted",
                "hub/db-overview",
                "hub/sizing",
            ],
        },
        {
            type: "category",
            label: "Configure Hub",
            items: [
                "hub/production-overview",
                "hub/high-availability",
                "hub/scalability",
                "hub/autoscaling",
                "hub/security",
                "hub/upgrades",
                "hub/aws-rds",
                "hub/data-residency",
                "hub/feature-flags",
                "hub/feature-lifecycle",
            ],
        },
        {
            type: "category",
            label: "Insights",
            items: [
                "hub/connections",
                "hub/connect-second-cluster",
                "hub/navigating",
                "hub/query-api",
                "hub/ai",
                "hub/use-cases",
                "hub/oidc",
            ],
        },
        {
            type: "category",
            label: "Identity",
            items: [
                "hub/administration-overview",
                "hub/iam",
                "hub/organizations",
                "hub/teams",
                "hub/users",
                "hub/robots",
                "hub/rbac",
                "hub/k8s-rbac",
                "hub/sso",
                "hub/oidc-configuration",
                "hub/entra-id",
                "hub/keycloak",
                "hub/generic",
            ],
        },
        "hub/reference",
    ],
    referenceSidebar: [
        "reference/index",
        "reference/cve-policy",
        {
            type: "category",
            label: "APIs",
            link: {
                type: "doc",
                id: "reference/apis/index",
            },
            items: [
                {
                    type: "link",
                    label: "Spaces API",
                    href: "/self-hosted-spaces/reference/",
                },
                {
                    type: "autogenerated",
                    dirName: "reference/apis",
                },
            ],
        },
        "reference/cli-reference",
        "reference/pricing",
        "reference/spaces-helm-reference",
        "reference/uxp-helm-reference",
        {
            type: "category",
            label: "Release Notes",
            items: [
                {
                    type: "autogenerated",
                    dirName: "reference/release-notes",
                },
            ],
        },
        {
            type: "category",
            label: "Usage",
            items: [
                {
                    type: "autogenerated",
                    dirName: "reference/usage",
                },
            ],
        },
    ],
};
